#!/bin/bash

# Placed by chef

#Make local backups if this machine has a scratch dir.
#test -d /mnt/scratch   && /usr/local/bin/fssnap.boot           /mnt/scratch  > /tmp/logs.boot 2>&1
/usr/local/bin/fssnap.boot           >  /tmp/log.fssnapS 2>&1
/usr/local/bin/fssnap.system  root   >> /tmp/log.fssnapS 2>&1
/usr/local/bin/fssnap.system  mythtv >> /tmp/log.fssnapS 2>&1
/usr/local/bin/fssnap.system  home   >> /tmp/log.fssnapS 2>&1

exit 0
