#!/bin/bash

# Placed by chef

# Look for kern errors
#egrep 'error|No free sequences' /tmp/kern.log.4 | egrep -q 'saa7164|s5h1411' && echo "critical tuner errors on `hostname`" | mail -s "urgent tuner errors " linuxtrader@gmail.com 9723425208@txt.att.net

kernlog="/var/log/kern.log"
#myip=$(ifconfig -a | grep Bcast | awk '{print $2}' 2> /dev/null)
myip=`/bin/hostname -I | sed 's/ //'`
hostname=$(hostname)
#to=$(cat /usr/local/etc/critical_mail)

egrep 'error|No free sequences' $kernlog | egrep -q 'saa7164|s5h1411' && (mail -s "Critical from $hostname" critical <<EOB
There are hung tuners on $myip

Found in $kernlog

`df -h /var`
--------------------------
This email is from /etc/cron.hourly/mythtv-anteater-hourly

EOB
)

# Store db backups if there is a thumbdrive
# technically not needed as these are in the mythtv lvm snap
test -d /media/PATRIOT && mkdir /media/PATRIOT/db_backups > /dev/null 2>&1
test -d /media/PATRIOT && mkdir /media/PATRIOT/geometry   > /dev/null 2>&1
test -d /media/PATRIOT && /usr/bin/rsync -a --no-o --no-g --delete /var/lib/mythtv/db_backups/ /media/PATRIOT/db_backups > /tmp/log.db_backups 2>&1

exit 0
