#!/bin/bash

# Placed by chef

#Notify everyone of available podcasts
/usr/local/bin/podcaststxt | /usr/bin/mime-construct --type text/html --subject "My DVR Podcasts" --to drmommarose@yahoo.com --to linuxtrader@gmail.com --file -

