#!/bin/sh
# /etc/cron.weekly/mythtv-database script - check and backup mythconverg tables
# Placed by chef
# Copyright 2005/12/02 2006/10/08 Paul Andreassen 
#                      2010 Mario Limonciello

set -e -u

DBNAME="mythconverg"
DEBIAN="--defaults-extra-file=/etc/mysql/debian.cnf"
now=`/bin/date '+%Y%m%d'`

/usr/bin/mysqlcheck $DEBIAN -s $DBNAME

/usr/share/mythtv/mythconverg_backup.pl

/usr/bin/logger -p daemon.info -i -t${0##*/} "$DBNAME checked and backedup."

/usr/bin/mythbackend --version > /var/lib/mythtv/db_backups/version.$now

# End of file.
