#!/bin/bash

# Placed by chef

me=`/bin/hostname -f | sed 's/ //'`
log=/var/tmp/${me}_thumbdrive.log
Slog=/var/tmp/${me}_fssnapS.log
# Copy backups if /media/PATRIOT is mounted, then unmount it.
cd /mnt/scratch > /dev/null 2>&1 || exit 0

test -d /media/PATRIOT || exit 0

cp -p *.fsa *.cpio *.sf *back /media/PATRIOT > ${log}  2>&1
mail -s "Thumbdrive backup complete/unmounted on $me" admin_local >> ${log} 2>&1 <<EOB 
Config backup to thumbdrive is complete on $me

`date`
`df -h /media/PATRIOT`
`ls -l /media/PATRIOT`
`cat ${Slog}`

--------------------------
This email is from /etc/cron.hourly/base-backup-hourly

EOB

/bin/umount /media/PATRIOT  >> ${log} 2>&1

exit 0
