#!/bin/bash

# Placed by chef

me=`/bin/hostname -f | sed 's/ //'`
# Copy backups if /media/PATRIOT is mounted, then unmount it.
test -d /media/PATRIOT && cp /mnt/scratch/*.fsa /media/PATRIOT && (mail -s "Thumbdrive complete/unmounted on $me" admin_local <<EOB
OS backup copy to thumbdrive is complete on $me

`date`
`df -h /media/PATRIOT`
`ls -l /media/PATRIOT`
`cat /tmp/log.fssnapS`

--------------------------
This email is from /etc/cron.hourly/base-backup-hourly

EOB
) > /tmp/log.thumbdrive 2>&1

test -d  /media/PATRIOT && /bin/umount /media/PATRIOT  >> /tmp/log.thumbdrive 2>&1

exit 0
