#!/bin/bash

# Placed by chef

/usr/bin/find /home/ant/.mythtv/remotecache -type f -atime +90 -print0 | xargs -0 /bin/rm -f

#Make some backups if /media/PATRIOT is mounted, then unmount it.
test -d /media/PATRIOT && /usr/local/bin/fssnap.boot                         > /tmp/logp.boot 2>&1
test -d /media/PATRIOT && /usr/local/bin/fssnap.system  root                 > /tmp/logp.root 2>&1
test -d /media/PATRIOT && /usr/local/bin/fssnap.system  mythtv               > /tmp/logp.myth 2>&1
 umount /media/PATRIOT                                                       > /tmp/logp.PATR 2>&1

#Make some backups if this machine has a scratch dir.
test -d /mnt/scratch   && /usr/local/bin/fssnap.boot           /mnt/scratch  > /tmp/logs.boot 2>&1
test -d /mnt/scratch   && /usr/local/bin/fssnap.system  root   /mnt/scratch  > /tmp/logs.root 2>&1
test -d /mnt/scratch   && /usr/local/bin/fssnap.system  mythtv /mnt/scratch  > /tmp/logs.myth 2>&1


